---
- name: install MySQL package
  apt: name=mysql-server state=present update_cache=yes

- name: install python-mysqldb mysql remote management
  apt: name=python-mysqldb state=present

# Configure MySQL Remote Access
- name: configure mysql remote access
  lineinfile: dest=/etc/mysql/my.cnf regexp="bind-address.*=.*" line="bind-address = 0.0.0.0"
  notify:
    - restart mysql


