- name: change root password
  user: name=root password="{{ root_password }}"

- name: add users
  user: name={{ item.name }} password="{{ item.password }}" shell=/bin/bash
  with_items: "{{ users }}"

- name: add authorized keys for users
  authorized_key: user={{ item.name }}
                  key="{{ lookup('file', item.public_key) }}"
  with_items: "{{ users }}"
  ignore_errors: true

- include: ssh-debian.yml
  when: (ansible_os_family|lower == 'debian')

- include: ssh-redhat.yml
  when: (ansible_os_family|lower == 'redhat')


