---
- name: install apache package
  apt: pkg=apache2
  register: result
  until: result|succeeded
  retries: 5

- name: install apache module packages
  apt: pkg={{ item }}
  with_items: "{{ apache.modules }}"
  register: result
  until: result|succeeded
  retries: 5



