---
- include: debian.yml
  when: (ansible_os_family|lower == 'debian')

- include: redhat.yml
  when: (ansible_os_family|lower == 'redhat')

- name: add phpinfo test page
  copy: src=test.php dest=/var/www/html owner=root group=root mode=644







